logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_HOST}:${REGISTRY_PORT}/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://${AUTH_HOST}:${AUTH_PORT}/uaa/users/current

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}