spring:
  data:
    mongodb:
      host: mongodb
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
      database: admin
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000
