spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
      database: admin
      port: ${MONGO_PORT}

server:
  servlet:
    context-path: /uaa
  port: ${PORT}
