security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: ${STATISTICS_SERVICE_PASSWORD}
      accessTokenUri: http://${AUTH_HOST}:${AUTH_PORT}/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
      database: admin
      port: ${MONGO_PORT}

server:
  servlet:
    context-path: /statistics
  port: ${PORT}

rates:
  url: https://exchangeratesapi.io/api
